"""initial_schema

Revision ID: fc77c7402109
Revises: 
Create Date: 2026-05-24 13:18:47.981771+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc77c7402109'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=False),
    sa.Column('park_factor_runs', sa.Float(), nullable=True),
    sa.Column('park_factor_hr', sa.Float(), nullable=True),
    sa.Column('park_factor_h', sa.Float(), nullable=True),
    sa.Column('park_factor_2b', sa.Float(), nullable=True),
    sa.Column('park_factor_3b', sa.Float(), nullable=True),
    sa.Column('park_factor_bb', sa.Float(), nullable=True),
    sa.Column('park_factor_so', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'season_year', name='uq_park_venue_season')
    )
    op.create_table('players',
    sa.Column('player_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name_first', sa.String(length=100), nullable=False),
    sa.Column('name_last', sa.String(length=100), nullable=False),
    sa.Column('name_display', sa.String(length=200), nullable=False),
    sa.Column('position_primary', sa.String(length=10), nullable=True),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.Column('team_abbr', sa.String(length=5), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('mlb_debut_date', sa.Date(), nullable=True),
    sa.Column('yahoo_player_key', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('user_leagues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('yahoo_league_key', sa.String(length=50), nullable=False),
    sa.Column('league_name', sa.String(length=200), nullable=True),
    sa.Column('season_year', sa.SmallInteger(), nullable=False),
    sa.Column('num_teams', sa.SmallInteger(), nullable=True),
    sa.Column('scoring_type', sa.String(length=50), nullable=True),
    sa.Column('current_week', sa.SmallInteger(), nullable=True),
    sa.Column('user_team_key', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yahoo_league_key', name='uq_yahoo_league_key')
    )
    op.create_table('games',
    sa.Column('game_pk', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team', sa.String(length=5), nullable=False),
    sa.Column('away_team', sa.String(length=5), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('season_year', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('home_score', sa.SmallInteger(), nullable=True),
    sa.Column('away_score', sa.SmallInteger(), nullable=True),
    sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=5), nullable=True),
    sa.Column('double_header', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_probable_pitcher_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['home_probable_pitcher_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('game_pk')
    )
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_table('league_scoring_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('stat_category', sa.String(length=50), nullable=False),
    sa.Column('points_value', sa.Float(), nullable=False),
    sa.Column('is_negative', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['user_leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'stat_category', name='uq_scoring_rule')
    )
    op.create_index(op.f('ix_league_scoring_rules_league_id'), 'league_scoring_rules', ['league_id'], unique=False)
    op.create_table('season_stats_batting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=True),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('obp', sa.Float(), nullable=True),
    sa.Column('slg', sa.Float(), nullable=True),
    sa.Column('woba', sa.Float(), nullable=True),
    sa.Column('wrc_plus', sa.Float(), nullable=True),
    sa.Column('iso', sa.Float(), nullable=True),
    sa.Column('babip', sa.Float(), nullable=True),
    sa.Column('bb_pct', sa.Float(), nullable=True),
    sa.Column('k_pct', sa.Float(), nullable=True),
    sa.Column('ev_avg', sa.Float(), nullable=True),
    sa.Column('barrel_pct', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct', sa.Float(), nullable=True),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('xba', sa.Float(), nullable=True),
    sa.Column('sprint_speed', sa.Float(), nullable=True),
    sa.Column('sb', sa.Integer(), nullable=True),
    sa.Column('cs', sa.Integer(), nullable=True),
    sa.Column('war', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_year', 'source', name='uq_season_batting')
    )
    op.create_index(op.f('ix_season_stats_batting_player_id'), 'season_stats_batting', ['player_id'], unique=False)
    op.create_table('season_stats_pitching',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.Float(), nullable=True),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('gs', sa.Integer(), nullable=True),
    sa.Column('batters_faced', sa.Integer(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('xfip', sa.Float(), nullable=True),
    sa.Column('siera', sa.Float(), nullable=True),
    sa.Column('k_pct', sa.Float(), nullable=True),
    sa.Column('bb_pct', sa.Float(), nullable=True),
    sa.Column('k_bb_pct', sa.Float(), nullable=True),
    sa.Column('hr_per_9', sa.Float(), nullable=True),
    sa.Column('gb_pct', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('avg_fastball_velo', sa.Float(), nullable=True),
    sa.Column('xwoba_against', sa.Float(), nullable=True),
    sa.Column('barrel_pct_against', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct_against', sa.Float(), nullable=True),
    sa.Column('xera', sa.Float(), nullable=True),
    sa.Column('war', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_year', 'source', name='uq_season_pitching')
    )
    op.create_index(op.f('ix_season_stats_pitching_player_id'), 'season_stats_pitching', ['player_id'], unique=False)
    op.create_table('user_rosters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('roster_position', sa.String(length=10), nullable=True),
    sa.Column('acquisition_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['user_leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'player_id', 'roster_date', name='uq_roster_slot')
    )
    op.create_index(op.f('ix_user_rosters_league_id'), 'user_rosters', ['league_id'], unique=False)
    op.create_index(op.f('ix_user_rosters_player_id'), 'user_rosters', ['player_id'], unique=False)
    op.create_index(op.f('ix_user_rosters_roster_date'), 'user_rosters', ['roster_date'], unique=False)
    op.create_table('batting_stats_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=True),
    sa.Column('team_abbr', sa.String(length=5), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('batting_order_slot', sa.SmallInteger(), nullable=True),
    sa.Column('opponent_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('pa', sa.SmallInteger(), nullable=False),
    sa.Column('ab', sa.SmallInteger(), nullable=False),
    sa.Column('h', sa.SmallInteger(), nullable=False),
    sa.Column('doubles', sa.SmallInteger(), nullable=False),
    sa.Column('triples', sa.SmallInteger(), nullable=False),
    sa.Column('hr', sa.SmallInteger(), nullable=False),
    sa.Column('rbi', sa.SmallInteger(), nullable=False),
    sa.Column('r', sa.SmallInteger(), nullable=False),
    sa.Column('bb', sa.SmallInteger(), nullable=False),
    sa.Column('so', sa.SmallInteger(), nullable=False),
    sa.Column('sb', sa.SmallInteger(), nullable=False),
    sa.Column('cs', sa.SmallInteger(), nullable=False),
    sa.Column('hbp', sa.SmallInteger(), nullable=False),
    sa.Column('sf', sa.SmallInteger(), nullable=False),
    sa.Column('gidp', sa.SmallInteger(), nullable=False),
    sa.Column('exit_velocity_avg', sa.Float(), nullable=True),
    sa.Column('barrel_pct', sa.Float(), nullable=True),
    sa.Column('hard_hit_pct', sa.Float(), nullable=True),
    sa.Column('xwoba', sa.Float(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['opponent_pitcher_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_pk', name='uq_batting_player_game')
    )
    op.create_index('ix_batting_player_date', 'batting_stats_daily', ['player_id', 'game_date'], unique=False)
    op.create_index(op.f('ix_batting_stats_daily_game_date'), 'batting_stats_daily', ['game_date'], unique=False)
    op.create_index(op.f('ix_batting_stats_daily_game_pk'), 'batting_stats_daily', ['game_pk'], unique=False)
    op.create_index(op.f('ix_batting_stats_daily_player_id'), 'batting_stats_daily', ['player_id'], unique=False)
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('at_bat_number', sa.SmallInteger(), nullable=False),
    sa.Column('pitch_number', sa.SmallInteger(), nullable=False),
    sa.Column('batter_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('pitch_type', sa.String(length=10), nullable=True),
    sa.Column('release_speed', sa.Float(), nullable=True),
    sa.Column('release_spin_rate', sa.Float(), nullable=True),
    sa.Column('release_extension', sa.Float(), nullable=True),
    sa.Column('pfx_x', sa.Float(), nullable=True),
    sa.Column('pfx_z', sa.Float(), nullable=True),
    sa.Column('plate_x', sa.Float(), nullable=True),
    sa.Column('plate_z', sa.Float(), nullable=True),
    sa.Column('launch_speed', sa.Float(), nullable=True),
    sa.Column('launch_angle', sa.Float(), nullable=True),
    sa.Column('hit_distance', sa.Float(), nullable=True),
    sa.Column('barrel', sa.SmallInteger(), nullable=True),
    sa.Column('events', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=1), nullable=True),
    sa.Column('zone', sa.SmallInteger(), nullable=True),
    sa.Column('stand', sa.String(length=1), nullable=True),
    sa.Column('p_throws', sa.String(length=1), nullable=True),
    sa.Column('inning', sa.SmallInteger(), nullable=True),
    sa.Column('inning_topbot', sa.String(length=3), nullable=True),
    sa.Column('outs_when_up', sa.SmallInteger(), nullable=True),
    sa.Column('balls', sa.SmallInteger(), nullable=True),
    sa.Column('strikes', sa.SmallInteger(), nullable=True),
    sa.Column('on_1b', sa.Integer(), nullable=True),
    sa.Column('on_2b', sa.Integer(), nullable=True),
    sa.Column('on_3b', sa.Integer(), nullable=True),
    sa.Column('estimated_woba_using_speedangle', sa.Float(), nullable=True),
    sa.Column('estimated_ba_using_speedangle', sa.Float(), nullable=True),
    sa.Column('fielder_2', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batter_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_pk', 'at_bat_number', 'pitch_number', name='uq_pitch_event')
    )
    op.create_index('ix_pitch_batter_game', 'pitches', ['batter_id', 'game_pk'], unique=False)
    op.create_index('ix_pitch_pitcher_game', 'pitches', ['pitcher_id', 'game_pk'], unique=False)
    op.create_index(op.f('ix_pitches_batter_id'), 'pitches', ['batter_id'], unique=False)
    op.create_index(op.f('ix_pitches_game_date'), 'pitches', ['game_date'], unique=False)
    op.create_index(op.f('ix_pitches_game_pk'), 'pitches', ['game_pk'], unique=False)
    op.create_index(op.f('ix_pitches_pitcher_id'), 'pitches', ['pitcher_id'], unique=False)
    op.create_table('pitching_stats_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season_year', sa.SmallInteger(), nullable=True),
    sa.Column('team_abbr', sa.String(length=5), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('role_flag', sa.String(length=2), nullable=True),
    sa.Column('opponent_team', sa.String(length=5), nullable=True),
    sa.Column('ip', sa.Float(), nullable=False),
    sa.Column('h', sa.SmallInteger(), nullable=False),
    sa.Column('er', sa.SmallInteger(), nullable=False),
    sa.Column('r', sa.SmallInteger(), nullable=False),
    sa.Column('bb', sa.SmallInteger(), nullable=False),
    sa.Column('so', sa.SmallInteger(), nullable=False),
    sa.Column('hr_allowed', sa.SmallInteger(), nullable=False),
    sa.Column('pitches_thrown', sa.SmallInteger(), nullable=True),
    sa.Column('batters_faced', sa.SmallInteger(), nullable=True),
    sa.Column('hbp', sa.SmallInteger(), nullable=False),
    sa.Column('wp', sa.SmallInteger(), nullable=False),
    sa.Column('wins', sa.SmallInteger(), nullable=False),
    sa.Column('losses', sa.SmallInteger(), nullable=False),
    sa.Column('saves', sa.SmallInteger(), nullable=False),
    sa.Column('holds', sa.SmallInteger(), nullable=False),
    sa.Column('blown_saves', sa.SmallInteger(), nullable=False),
    sa.Column('quality_starts', sa.SmallInteger(), nullable=False),
    sa.Column('gb_pct', sa.Float(), nullable=True),
    sa.Column('fip', sa.Float(), nullable=True),
    sa.Column('xwoba_against', sa.Float(), nullable=True),
    sa.Column('fantasy_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_pk', name='uq_pitching_player_game')
    )
    op.create_index('ix_pitching_player_date', 'pitching_stats_daily', ['player_id', 'game_date'], unique=False)
    op.create_index(op.f('ix_pitching_stats_daily_game_date'), 'pitching_stats_daily', ['game_date'], unique=False)
    op.create_index(op.f('ix_pitching_stats_daily_game_pk'), 'pitching_stats_daily', ['game_pk'], unique=False)
    op.create_index(op.f('ix_pitching_stats_daily_player_id'), 'pitching_stats_daily', ['player_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_mean', sa.Float(), nullable=False),
    sa.Column('predicted_p10', sa.Float(), nullable=True),
    sa.Column('predicted_p90', sa.Float(), nullable=True),
    sa.Column('actual_points', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_pk'], ['games.game_pk'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_pk', 'model_version', name='uq_prediction')
    )
    op.create_index(op.f('ix_predictions_game_pk'), 'predictions', ['game_pk'], unique=False)
    op.create_index(op.f('ix_predictions_player_id'), 'predictions', ['player_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_date'), 'predictions', ['prediction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_prediction_date'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_player_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_game_pk'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_pitching_stats_daily_player_id'), table_name='pitching_stats_daily')
    op.drop_index(op.f('ix_pitching_stats_daily_game_pk'), table_name='pitching_stats_daily')
    op.drop_index(op.f('ix_pitching_stats_daily_game_date'), table_name='pitching_stats_daily')
    op.drop_index('ix_pitching_player_date', table_name='pitching_stats_daily')
    op.drop_table('pitching_stats_daily')
    op.drop_index(op.f('ix_pitches_pitcher_id'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_game_pk'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_game_date'), table_name='pitches')
    op.drop_index(op.f('ix_pitches_batter_id'), table_name='pitches')
    op.drop_index('ix_pitch_pitcher_game', table_name='pitches')
    op.drop_index('ix_pitch_batter_game', table_name='pitches')
    op.drop_table('pitches')
    op.drop_index(op.f('ix_batting_stats_daily_player_id'), table_name='batting_stats_daily')
    op.drop_index(op.f('ix_batting_stats_daily_game_pk'), table_name='batting_stats_daily')
    op.drop_index(op.f('ix_batting_stats_daily_game_date'), table_name='batting_stats_daily')
    op.drop_index('ix_batting_player_date', table_name='batting_stats_daily')
    op.drop_table('batting_stats_daily')
    op.drop_index(op.f('ix_user_rosters_roster_date'), table_name='user_rosters')
    op.drop_index(op.f('ix_user_rosters_player_id'), table_name='user_rosters')
    op.drop_index(op.f('ix_user_rosters_league_id'), table_name='user_rosters')
    op.drop_table('user_rosters')
    op.drop_index(op.f('ix_season_stats_pitching_player_id'), table_name='season_stats_pitching')
    op.drop_table('season_stats_pitching')
    op.drop_index(op.f('ix_season_stats_batting_player_id'), table_name='season_stats_batting')
    op.drop_table('season_stats_batting')
    op.drop_index(op.f('ix_league_scoring_rules_league_id'), table_name='league_scoring_rules')
    op.drop_table('league_scoring_rules')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_table('games')
    op.drop_table('user_leagues')
    op.drop_table('players')
    op.drop_table('park_factors')
    # ### end Alembic commands ###
